name: Dependency Check

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    
    - name: Check for vulnerabilities
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...
    
    - name: Update dependencies
      run: |
        go get -u ./...
        go mod tidy
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'Auto-update dependencies'
        body: |
          Automated dependency update
          
          - Updated Go modules to latest versions
          - Checked for security vulnerabilities
        branch: auto-update-deps
